### ISSUE TITLE
好像缺失了指定训练和测试的txt文件

### ISSUE THREAD

**Issue by ZexiChen502** [MediaBrain-SJTU/MoLA#1]
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm 2023.1.3\plugins\python\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm 2023.1.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\sci_job\MoLA\MoLA-main\train.py", line 305, in <module>
    trainer = MTLTrainer(args)
  File "D:\sci_job\MoLA\MoLA-main\train.py", line 22, in __init__
    self.benchmark = get_benchmark_class(args.benchmark)(args)
  File "D:\sci_job\MoLA\MoLA-main\mola_code\benchmarks\vlcs.py", line 271, in __init__
    'train': VLCS(split='train'),
  File "D:\sci_job\MoLA\MoLA-main\mola_code\data\datasets\my_vlcs.py", line 80, in __init__
    with open(each_split_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\sci_job\\MoLA\\MoLA-main\\datasets\\VLCS\\VLCS\\PASCAL_train.txt'
python-BaseException

Process finished with exit code 1

**Comment by JasonGuo1** [comment]
同问，非常好的工作，请教作者这些文件如何获取，谢谢

**Comment by Xinggaojie765** [comment]
> Traceback (most recent call last): File "D:\Program Files\JetBrains\PyCharm 2023.1.3\plugins\python\helpers\pydev\pydevd.py", line 1496, in _exec pydev_imports.execfile(file, globals, locals) # execute the script File "D:\Program Files\JetBrains\PyCharm 2023.1.3\plugins\python\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile exec(compile(contents+"\n", file, 'exec'), glob, loc) File "D:\sci_job\MoLA\MoLA-main\train.py", line 305, in trainer = MTLTrainer(args) File "D:\sci_job\MoLA\MoLA-main\train.py", line 22, in **init** self.benchmark = get_benchmark_class(args.benchmark)(args) File "D:\sci_job\MoLA\MoLA-main\mola_code\benchmarks\vlcs.py", line 271, in **init** 'train': VLCS(split='train'), File "D:\sci_job\MoLA\MoLA-main\mola_code\data\datasets\my_vlcs.py", line 80, in **init** with open(each_split_file, 'r') as f: FileNotFoundError: [Errno 2] No such file or directory: 'D:\sci_job\MoLA\MoLA-main\datasets\VLCS\VLCS\PASCAL_train.txt' python-BaseException
> 
> Process finished with exit code 1

Have you solved your problem? How did you solve it
